apiVersion: v1
kind: Service
metadata:
  name: multi-cloud-service
spec:
  selector:
    app: multi-cloud
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
